### ISSUE TITLE
GsfException: [-23] GSF End of File Encountered

### ISSUE THREAD

**Issue by gkvishwab** [UKHO/gsfpy#183]
* Generic Sensor Format for Python version:2.0.0
* Python version:3.7.12
* Operating System: Google Colab

-------------------------------------------------------------
My Code:

`from ctypes import string_at

from gsfpy3_08 import open_gsf
from gsfpy3_08.enums import RecordType

with open_gsf("Path_to_gsf_file.gsf") as gsf_file:
    # Note - file is closed automatically upon exiting 'with' block
    _, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)`

---------------------------------------------------------------------------------------------
Error 

GsfException                              Traceback (most recent call last)
[<ipython-input-7-9a72acf406d1>](https://localhost:8080/#) in <module>()
      6 with open_gsf("20211104_162722-S-3-7500-0001_M3.gsf") as gsf_file:
      7     # Note - file is closed automatically upon exiting 'with' block
----> 8     _, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)

[/usr/local/lib/python3.7/dist-packages/gsfpy3_08/__init__.py](https://localhost:8080/#) in read(self, desired_record, record_number)
     99 
    100         _handle_failure(
--> 101             gsfRead(self._handle, desired_record, byref(data_id), byref(records))
    102         )
    103 

[/usr/local/lib/python3.7/dist-packages/gsfpy3_08/__init__.py](https://localhost:8080/#) in _handle_failure(return_code)
    171     """
    172     if return_code == _ERROR_CODE:
--> 173         raise GsfException()

GsfException: [-23] GSF End of File Encountered

**Comment by jiriklic** [comment]
Hi @gkvishwab, thanks for your question and sorry for the delayed reply.

Your `GsfException` says that you have reached the end of the file. That Error originated in the compiled C code of `GSFlib`. For licensing reasons, we can only distribute the `gsfpy` with pre-compiled C binaries. However, if you would like to have a look into the  source code of `GSFlib` that `gsfpy` is using, it can be downloaded for further reference from the **[Leidos website](https://www.leidos.com/products/ocean-marine)**.

The error code `-23` is defined in `gsf.c` file as:
```c
#define GSF_READ_TO_END_OF_FILE -23
```

### What does it mean for you:

#### Option-1 

You are either trying to open the empty file or have no record of the type `RecordType.GSF_RECORD_COMMENT`. If your package was properly installed, and you try to use the sample file located in this repository,
```
gsfpy/tests/test_data/GSF3_08_test_file.gsf
```
then the following code example
```python
from ctypes import string_at

from gsfpy3_08 import open_gsf
from gsfpy3_08.enums import RecordType

with open_gsf("gsfpy/tests/test_data/GSF3_08_test_file.gsf") as gsf_file:
    # Note - file is closed automatically upon exiting 'with' block
    _, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)

    # Note use of ctypes.string_at() to access POINTER(c_char) contents of
    # c_gsfComment.comment field.
    print(string_at(record.comment.comment))
```

should return something like the following output
```
b'Bathy converted from HIPS file: M:\\CCOM_Processing\\CARIS_v9\\HIPS\\HDCS_Data\\EX1604\\Okeanos_2016\\2016-083\\0029_20160323_185603_EX1604_MB'
```

#### Option-2

The `[-23]` Error can also occur if you try to read a file that has already reached the end. For example, the following code
```python
gsf_file = open_gsf("gsfpy/tests/test_data/GSF3_08_test_file.gsf")

print("read first time")
_, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)
print(string_at(record.comment.comment))

print("read second time")
_, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)
print(string_at(record.comment.comment))

print("read third time")
_, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)
print(string_at(record.comment.comment))
```

will result in something like this:
```
read first time
b'Bathy converted from HIPS file: M:\\CCOM_Processing\\CARIS_v9\\HIPS\\HDCS_Data\\EX1604\\Okeanos_2016\\2016-083\\0029_20160323_185603_EX1604_MB'
read second time
b'SVP_FILE_NAME: CONVERT - J:\\Year\\2016\\EX1604\\Raw\\EM302_MB\\083\\0029_20160323_185603_EX1604_MB.all'
read third time
---------------------------------------------------------------------------
GsfException                              Traceback (most recent call last)
Input In [2], in <cell line: 15>()
     13 # read third time
     14 print("read third time")
---> 15 _, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)
     16 print(string_at(record.comment.comment))

File ~/src/gsfpy-example/.venv/lib/python3.8/site-packages/gsfpy3_08/__init__.py:100, in GsfFile.read(self, desired_record, record_number)
     96 data_id.record_number = record_number
     98 records = c_gsfRecords()
--> 100 _handle_failure(
    101     gsfRead(self._handle, desired_record, byref(data_id), byref(records))
    102 )
    104 return data_id, records

File ~/src/gsfpy-example/.venv/lib/python3.8/site-packages/gsfpy3_08/__init__.py:173, in _handle_failure(return_code)
    167 """
    168 Error handling logic
    169 :param return_code: The return code from one of functions in the gsfpy3_08.bindings
    170                     package
    171 """
    172 if return_code == _ERROR_CODE:
--> 173     raise GsfException()

GsfException: [-23] GSF End of File Encountered
```

It means that the file had two records of type `RecordType.GSF_RECORD_COMMENT`, after which it reached the end. Trying to read for the third time triggered the exception. In such scenario you can choose to handle the Exceptions inside of the try block:

```python
from ctypes import string_at

from gsfpy3_08 import open_gsf, GsfException
from gsfpy3_08.enums import RecordType

gsf_file = open_gsf("gsfpy/tests/test_data/GSF3_08_test_file.gsf")

while True:
    try:
        _, record = gsf_file.read(RecordType.GSF_RECORD_COMMENT)
        print(string_at(record.comment.comment))
    except GsfException as e:
        print(e.error_message)
        break
```

and you should see the following output:
```
b'Bathy converted from HIPS file: M:\\CCOM_Processing\\CARIS_v9\\HIPS\\HDCS_Data\\EX1604\\Okeanos_2016\\2016-083\\0029_20160323_185603_EX1604_MB'
b'SVP_FILE_NAME: CONVERT - J:\\Year\\2016\\EX1604\\Raw\\EM302_MB\\083\\0029_20160323_185603_EX1604_MB.all'
GSF End of File Encountered
```

I hope that helps :thumbsup:
