### ISSUE TITLE
Add support for GSF 3.09

### ISSUE THREAD

**Issue by lmarsden** [UKHO/gsfpy#98]
Currently gsfpy is bundled with version 3.08 of libgsf. The sister project UKHO/libgsf provides built artefacts for both 3.08 and 3.09 of libgsf.

Update the gsfpy project documentation with instructions on how to run gsfpy with versions of libgsf other than 3.08.

**ACs**
* Documentation: Instructions on how to run gsfpy with libgsf>3.08 are present in project documentation.

**Comment by eriffon** [comment]
Just wondering is someone is already working on or intends to work on adapting gsfpy to run with gsflib 3.09? I've noticed that there are important changes between gsflib 3.08 and 3.09 which break the compatibility of gsfpy with gsflib > 3.08. I might be interested in issuing a pull request for that purpose if no one else intends to do so, but I still don't have a timeframe in mind when I would do so.

**Comment by lmarsden** [comment]
@eriffon, thanks for highlighting this. The work is currently on our backlog, but has not yet been given a concrete projected completion date. If you would like to submit a PR that would be most welcome. Else we will look at raising the priority of this issue. If you wish to get in touch with us directly you can do so at datascienceandengineering@UKHO.gov.uk - this is quite a new project and we are always interested in finding out more about specific GSF use cases and the GSF community.
